name: Deploy via self-hosted runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]  # Runs *on your EC2*

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t dotnet-api .

    - name: Stop and remove old container
      run: |
        docker stop dotnet-api || true
        docker rm dotnet-api || true

    - name: Run new container
      run: |
        docker run -d --name dotnet-api -p 8080:80 dotnet-api
