name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dotnet-api:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/dotnet-api:latest

  postman-tests:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (without push)
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true # <--- loads image into local Docker engine
          tags: api:test # <--- local tag used for running the container

      - name: Test MySQL Connection to remote
        run: |
          docker run -dit --name mysqldb mysql:8.0 mysql -h${{ secrets.MYSQL_HOST }} -u${{ secrets.MYSQL_USERNAME }} -p${{ secrets.MYSQL_PASSWORD }}

      - name: Run container 
        run: |
          docker run -d --name test-api --rm -p 80:8080 api:test
          sleep 4

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests
        run: |
          newman run Tests/MoneyBankService.postman_collection.json \
            --reporters cli,junit \
            --reporter-junit-export newman-results.xml

      - name: Upload test results
        if: always()  # Ensures this runs even if Newman fails
        uses: actions/upload-artifact@v4
        with:
          name: newman-results
          path: newman-results.xml
          
  deploy:
    needs: build-and-push
    runs-on: [self-hosted]  # EC2 intance

    steps:
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Pull latest image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/dotnet-api:latest

    - name: Stop and remove old container
      run: |
        docker stop dotnet-api || true
        docker rm dotnet-api || true

    - name: Run new container
      run: docker run -d --name dotnet-api -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/dotnet-api:latest

 